include: package:pedantic/analysis_options.yaml
analyzer:
  strong-mode:
    implicit-casts: false
linter:
  rules:
    - await_only_futures
    - implementation_imports
    - prefer_typing_uninitialized_variables
    - unnecessary_const
    - unnecessary_new
